### ISSUE TITLE
Completely silent setup

### ISSUE THREAD

**Issue by zeugfr** [poxet/Influx-Capacitor#11]
Not sure I missed something, but I don't find it easy to automate the Influx-Capacitor setup without having sometimes a problem.

I succeded it by creating the "C:\ProgramData\Thargelion\Influx-Capacitor\*.xml" directories and files, and then call the msi setup with /q parameter, but if, for example, the influxdb server is temporary unreachable, setup will be stuck on the Influx-Capacitor console with the error message.

Would it be possible to have a command line parameter that always exits silently (no blocking) with just a message and an exit code to be checked ?

Many thanks for this usefull tool !

**Comment by poxet** [comment]
There needs to be a simple way of entering database connection information. Do you mean that this can be done after the installation? That would actually make things allot less complicated for the installation process. And also perhaps better usage. I will look into that.

Are you a coder, or do you work with operations?

**Comment by zeugfr** [comment]
Yes, it could be better to separate silent installation (without config, leaving service stopped) and configuration.
I am not a coder, i work on operation (we are building an automation system for on-demand virtual services, for internal users) and I think Influx-Capacitor is a very good candidate for telemetry of windows VMs (and windows applications like sql server).

**Comment by poxet** [comment]
I will try to make this happen during next week.

Another idea... If you have any generic xml configuration files that is good for monitoring. It whould be great to add them to the project. I would like some standard template included, that would make it easier to get started for new users.

**Comment by zeugfr** [comment]
Yes I can give you sample config files, juste have to make some cleanup on mine.

**Comment by poxet** [comment]
Thanks for the samples. They are merged into the project.

The installation should be quiet now. However, it might need some more testing.

**Comment by zeugfr** [comment]
It seems that the service is still started even if the config is not done in silent setup.
Is it possible to leave it stopped or add a command line parameter to chose if it is started or not after setup ?

**Comment by poxet** [comment]
That is true. The service starts even though there is no setup. The idea was that it should not crash when there is no setup. But you are right. It is better that it is not started at all.

**Comment by poxet** [comment]
I am closing this issue, if there is still a demand for it I will reopen it again.
