### ISSUE TITLE
Dual feed (more than 1 influxDB target)

### ISSUE THREAD

**Issue by zeugfr** [poxet/Influx-Capacitor#12]
I think my request is perhaps not-so-simple to implement, but it would be interesting if we could define more than 1 InfluxDB target.
In my environment we would like to feed 2 different InfluxDB (on 2 different sites), and a simple approach would be to dual feed (other approaches like InfluxDB proxy or clusters do not seem to be reliable for the moment).
What do you think about that ?

**Comment by poxet** [comment]
You mean to have the same data on one machine sent to several Influx databases at once? Or, to have some metrics sent to one database and and some to another other?

To have all data sent to more than one database would not be so hard actually. I do not have the need for it, but if you do, then I will have a look at it. :)

**Comment by zeugfr** [comment]
Yes, all data to 2 InfluxDB :)
Thanks !

**Comment by poxet** [comment]
From version 1.0.11 it is possible to specify several database targets (as many as you like). It cannot be done using the console application, you have to do it by adding another Database element in one of the config files.
