### ISSUE TITLE
Metadata Counter

### ISSUE THREAD

**Issue by poxet** [poxet/Influx-Capacitor#25]
Send metadata about the performance of the influx-capacitor to influxDB as a separate counter.

Record the time it takes to read counters, information about the queue and by how much the Exact counter is adjusted to be in sync.

This feature should be optional and configurable.

**Comment by zeugfr** [comment]
Good idea, with this we can monitor the health of our Influx-Capacitor agents :)

**Comment by poxet** [comment]
Minor version 1.0.8.55 now have some metadata counters. Ill test them some more, before I release a new major version.

**Comment by poxet** [comment]
In version 1.0.15 there is metadata written to "Influx-Capacitor-Metadata"
