### ISSUE TITLE
"Not a valid Win32 application" on server 2003 R2 x64

### ISSUE THREAD

**Issue by dedward** [poxet/Influx-Capacitor#32]
I can't seem to get this to run on server2003, even if I rebuild for 32 bit or 64 bit only.

Any idea what I'm missing here?

**Comment by poxet** [comment]
Perhaps there is a nuget package that the project is dependent on that is the problem.

If you buid the project and then just try to start "Tharga.Influx-Capacitor.Console". What type of exception do you get then?

**Comment by dedward** [comment]
It works fine on the machine I'm building it on (Win7)- I'm afraid I don't have VS installed on a 2003 machine to test it.

**Comment by dedward** [comment]
I can do pretty much anything in order to figure this out though... let me know how I can help.

**Comment by dedward** [comment]
I think we can chalk it up to .net 4.5 not working on 2003...

**Comment by poxet** [comment]
Okey, there is some code that needs .NET 4.5 to run, so reqrite it to a lower .NET version would be allot of work.

How about getting the "Remote machine(s) monitoring" to work. Then you could run the monitoring from a newer machine, would that solve the problem? Do you know if it is possible to monitor a 2003 server from performance monitor on a 2012 server?

**Comment by dedward** [comment]
I think that's a great idea - in terms of using this thing in an enterprise (like I'm trying to) - being able to set up a dedicated host to gather data and push it to influxdb rather than installing IC on every machine I want to monitor has some obvious benefits, not the least of which is ease of configuration.

I don't know specifically if 2012 -> 2003 would work, but I have no reason to think it wouldn't - I mean I can monitor all of them from a Win7 workstation running Performance Monitor without issue.

**Comment by poxet** [comment]
Allright. I will close this issue, and try to fix the "Remote machine(s) monitoring" as soon as possible. If it does not solve the problem we can repoen the issue or create a new one.
