### ISSUE TITLE
Not all instances showing

### ISSUE THREAD

**Issue by dedward** [poxet/Influx-Capacitor#33]
I'm not entirely sure where to go with this one... but I'm trying to pull counters from 
\.NET CLR Remoting - Remote Calls/sec

Locally from performance monitor, I can see all the instances on the machine.
Influx Capacitor seems only able to see itself, and the _Global_ instance - both which indicate 0 all the time.

_Global_ on the performance-monitor view shows me what I'd expect.

It smells like a permission issue, but even with the service running as the same user as I use interactively, I get different results.

Any help greatly appreciated.

**Comment by poxet** [comment]
I tried this for a config...

<Influx-Capacitor>
  <CounterGroups>
    <CounterGroup Name="NET-CLR-Remoting" SecondsInterval="10" RefreshInstanceInterval="10" CollectorEngineType="Safe">
      <Counter>
        <CategoryName>.NET CLR Remoting</CategoryName>
        <CounterName>Remote Calls/sec</CounterName>
        <InstanceName>*</InstanceName>
	  </Counter>
    </CounterGroup>
  </CounterGroups>
</Influx-Capacitor>

What I could see was that performance monitor shows the same number of instances as Influx-Capacitor does. (However, all my values was 0, in both the monitor and Influx-Capacitor)

Is this what you tried to do?

I have seen some issue with windows running on other languages, Swedish for instance, but I think that theese issues have been solved.

**Comment by dedward** [comment]
Yes.. that's exactly what I did, and exactly the result  I see when running it on server 2012 core. 
There are other instances running on the same box, and they just don't show up. If I specify them by name instead of using * I just get no results.

When I try powershell Get-Counter locally on the server, I see them all, and if I try remotely from Performance Monitor on my workstation, I see them as well.  I'm unable to replicate the problem in any other tool so far.

When I try influx capacitor with the same query on a win7 workstation, it shows me all the various instances running as expected.

Is IC a 32 or 64 bit app? There was an issue with counters and word-size, though I'm not sure that's what's going on... because I'm not seeing the IIS (w3m*) instances either.

I'll google up the language thing.. who knows. It still smells like pemissions of some kind..

The same behaviour seems to exist across all the .NET CLR counter groups.

**Comment by dedward** [comment]
It looks like the problem may be that IC is running as a 32 bit, which means it can't see 64 bit performance counters.
Will the build tolerate turning off "Prefer 32 bit" in the build options? that should take care of it.

**Comment by poxet** [comment]
Allright. Ill have a look at the build configuration for next deploy.

**Comment by poxet** [comment]
In version 1.16 I changed "Prefer 32 bit" to false. Please tell me if that did not help.
