### ISSUE TITLE
Auto limiting of percent based counters

### ISSUE THREAD

**Issue by kirillkovalenko** [poxet/Influx-Capacitor#34]
Some percent based counters are known for returning values more than 100, which could be confusing for further processing. This is "behavior is by design" as Microsoft says: https://support.microsoft.com/en-us/kb/310067 :-1: 
I suggest providing a way to fix percent based values that are more than 100.

**Comment by poxet** [comment]
Perhaps a setting for max values for the counter should do it. I am adding it as an enhancement.

**Comment by tbolon** [comment]
I have just submitted a new PR to fix this issue.

**Comment by poxet** [comment]
It is merged into master. Great work! Thanks!
