### ISSUE TITLE
RuntimeBinderException on InfluxDataSenderConfiguration constructor

### ISSUE THREAD

**Issue by tbolon** [poxet/Influx-Capacitor#38]
Hi,

It seems the new InfluxDataSenderConfiguration constructor raises a RuntimeBinderException on `Properties.Url = url` because the dynamic object is not initialized.

It seems you should add `Properties = new System.Dynamic.ExpandoObject();` for the code to execute.

**Comment by poxet** [comment]
Thanks for the contribution!!!
