### ISSUE TITLE
Does not work with 0.10

### ISSUE THREAD

**Issue by kirillkovalenko** [poxet/Influx-Capacitor#42]
I've just updated my back-end server to InfluxDB 0.10.0 and the capacitor service is now unable to send the data there. I guess, the problem is that the service uses `InfluxVersion.Auto` when creating a database connection object instance. 

It seems that you use your own version of InfluxDB.NET.dll, because the original one does not have `InfluxVersion` enumeration at all, however I could not find the source code of your fork. I suppose it's the InfluxDB.NET.dll code that needs to be fixed for 0.10. 

Please fix and provide a link the source code.

**Comment by poxet** [comment]
The component I use for communicating with influxDB is under development. I am contributing to that project too. As soon as it is done I will try to get it working here too.

**Comment by kirillkovalenko** [comment]
Do you mean [ziyasal/InfluxDB.Net](https://github.com/ziyasal/InfluxDB.Net) code by that component? It looks abandoned.

**Comment by poxet** [comment]
As of version 1.0.16 it works with influxDB version 0.10.0.
