### ISSUE TITLE
Colon not working in config-server context of console

### ISSUE THREAD

**Issue by mjlyon** [poxet/Influx-Capacitor#43]

**Comment by mjlyon** [comment]
Even with the on-screen keyboard, the input of a colon is not accepted.  

2012R2, using the latest stable 
<img width="1326" alt="screen shot 2016-02-11 at 3 54 03 pm" src="https://cloud.githubusercontent.com/assets/786306/12990319/c4f126ca-d0d7-11e5-94b7-a0ac23ab2fb5.png">

**Comment by poxet** [comment]
This is the same issue as #23. The input is valuble and I will have a look at this issue. It seems that there are many users that want this do be resolved.

**Comment by poxet** [comment]
As of version 1.0.16 this should work. Please get back to me if it does not.
