### ISSUE TITLE
Allow mutivalued InstanceName property for a Counter

### ISSUE THREAD

**Issue by kirillkovalenko** [poxet/Influx-Capacitor#48]
Use case: I'm trying to peek various memory related counters for all the Microsoft Exchange processes. The ability to use wild-cards helps a lot, e.g. I use `<InstanceName>*Exchange*</InstanceName>` to grab all the processes that have Exchange in their names. But this does not cover all the exchange processes, because there is store, msftefd, msftesql, etc. For each of those, apparently  I'll have to copy / paste the same `Counter` section. Instead, it would be nice to use several `InstanceName` sections within a single `Counter` section.

**Comment by tbolon** [comment]
Could this be related to #41 ? With Filters, you could use a regular expression pattern similar to `"Exchange|store|msftefd|..."` which will include all the instances you mentionned ?

**Comment by kirillkovalenko** [comment]
I did some code for this. Please take a look and let me know what you thinkz

**Comment by poxet** [comment]
Great work! Three issues taken care of. Thanks!!!
