### ISSUE TITLE
Ability to define http request timeout to send data

### ISSUE THREAD

**Issue by marcelopetersen** [poxet/Influx-Capacitor#56]
According to https://github.com/poxet/Influx-Capacitor/issues/47, nowadays is not possible to define the timeout of http request sent to influxdb.

Looking at MSDN documentation, the default value of the timeout property is 100 seconds (100.000 miliseconds) and I think this very high. If influxdb is slow to respond, probably the queue will increase fast (I don't know what behavior of capacitor about retries when sending collected data results in error, reenquee?).

Have control of timeout property should help a lot.

Documentation:
https://msdn.microsoft.com/en-us/library/system.net.httpwebrequest.timeout(v=vs.100).aspx

**Comment by poxet** [comment]
I will check to se if I can provide an update for this in the component project used to send data to influxDB (https://github.com/poxet/InfluxDB.Net)

**Comment by poxet** [comment]
I have completed this in the develop branch now. If you want to use it right away, it is in the continuous build version 1.0.17.100. (http://influx-capacitor.com/Home/Download)

**Comment by marcelopetersen** [comment]
Tks!
