### ISSUE TITLE
Stops sending data when instance disappers?

### ISSUE THREAD

**Issue by dedward** [poxet/Influx-Capacitor#59]
It appears that IC stops sending data when a counter instance momentarily disappeas, such as when a service is restarted.

I'm seeing this with IIS counters - if IIS is restarted, IC must also be restarted or no data shows up.

**Comment by poxet** [comment]
First I thought that this was a bug. But then I remember a setting for it. :)

You can add an attribute named RefreshInstanceInterval  to the element CounterGroup. That setting tells Influx-Capacitor how often it should refresh the counters. The default value is 0, so the counter will never refresh automatically.

Read more about this setting here... https://github.com/poxet/Influx-Capacitor#configuration
