### ISSUE TITLE
Influx-Capacitor is not compatible yet with InfluxDB 0.11

### ISSUE THREAD

**Issue by framiere** [poxet/Influx-Capacitor#60]
I would recommend to add a line in the InfluxCapacitor description that it is not yet compatible with InfluxDB 0.11.

The problem lies in InfluxDB.Net that is very specific about InfluxDB version

Please see https://github.com/ziyasal/InfluxDB.Net/blob/master/InfluxDB.Net/Client/InfluxDbClientAutoVersion.cs#L24

Cheers!

**Comment by poxet** [comment]
You are righ. Also I will contribute to InfluxDB.Net to have it support new versions.

**Comment by Confusingboat** [comment]
Interestingly enough, I have a single installation of Influx-Capacitor v1.0.16.0 (that for some reason has not been auto-updated) which appears to work with InfluxDB 0.11, while all my v1.0.17.0 installations do not.

**Comment by poxet** [comment]
Version 0.11.x should work from version 1.0.17.108 (http://influx-capacitor.com/Home/Download). I have yet not confirmed that it it so, but the packages are updated anyway. Will test before I create a new official package.

**Comment by Papyruse** [comment]
Same problem here, InfluxDB in 0.12 and the release 1.0.17.108 of Influx-Capacitor  doesn't work (Could not etablish a connection to the database).

**Comment by poxet** [comment]
Working on version 0.12 now,..

**Comment by poxet** [comment]
Just pushed version 1.0.18 with support for influxdb version 0.11 and 0.12.
