### ISSUE TITLE
Application stops collecting data

### ISSUE THREAD

**Issue by bondido** [poxet/Influx-Capacitor#64]
Hi,
I'm facing the issue as follows:
I have Influx-capacitor (checked both 1.18.0.0 and 1.18.0.3 version) installed on one of my hosts and try to collect perfmon counters from couple of remote machines. I use console version just to watch it working, but it behaves the same way with the service version. After some time from the counter start I can see  a sequence of messages like:

_Engine A: Dropping X steps.
Engine A: Dropping X steps.
Engine A: Dropping X steps.
Engine A: Dropping X steps.
Engine B: Dropping X steps.
Engine A: Dropping X steps.
Engine A: Dropping X steps.
Engine A: Missing 6 cycles. Resetting and starting over._

...and the application stops logging data into database. The only way to make it functional again is restart (in case of service - kill the process - as stop action on the service is timing out).
I use InfluxDB ver. 0.12.2 and Grafana ver. 3.0.0-beta7 (also tried 3.0.0-beta5)

Best Regards
Tomasz

**Comment by poxet** [comment]
It looks like you are using the "Exact"-Collector. Try using the "Safe"-Collector instead and see what happens.

The Exact-Collector is unstable and I am actually thinking of discontinuing that one.

**Comment by bondido** [comment]
You're right - I was using "Exact" mode.
I've switched to "Safe" and as for now - it's working and collecting data longer than ever before.

Thanks.
